// <auto-generated/>
#pragma warning disable CS0618
using Kursa.Infrastructure.MoodlewareAPI.Client.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Kursa.Infrastructure.MoodlewareAPI.Client.Core_webservice_get_site_info
{
    /// <summary>
    /// Builds and executes requests for operations under \core_webservice_get_site_info
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Core_webservice_get_site_infoRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_webservice_get_site_info.Core_webservice_get_site_infoRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Core_webservice_get_site_infoRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/core_webservice_get_site_info", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_webservice_get_site_info.Core_webservice_get_site_infoRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Core_webservice_get_site_infoRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/core_webservice_get_site_info", rawUrl)
        {
        }
        /// <summary>
        /// Proxy request to the Moodle instance and return JSON/text response.
        /// </summary>
        /// <returns>A <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_webservice_get_site_info.Core_webservice_get_site_infoPostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_webservice_get_site_info.Core_webservice_get_site_info422Error">When receiving a 422 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_webservice_get_site_info.Core_webservice_get_site_infoPostResponse?> PostAsync(global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreWebserviceGetSiteInfoRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_webservice_get_site_info.Core_webservice_get_site_infoPostResponse> PostAsync(global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreWebserviceGetSiteInfoRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "422", global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_webservice_get_site_info.Core_webservice_get_site_info422Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_webservice_get_site_info.Core_webservice_get_site_infoPostResponse>(requestInfo, global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_webservice_get_site_info.Core_webservice_get_site_infoPostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Proxy request to the Moodle instance and return JSON/text response.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreWebserviceGetSiteInfoRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreWebserviceGetSiteInfoRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_webservice_get_site_info.Core_webservice_get_site_infoRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_webservice_get_site_info.Core_webservice_get_site_infoRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_webservice_get_site_info.Core_webservice_get_site_infoRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
