// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Kursa.Infrastructure.MoodlewareAPI.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CoreCourseSearchCoursesRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Search criteria name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest.CoreCourseSearchCoursesRequest_criterianame? Criterianame { get; set; }
#nullable restore
#else
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest.CoreCourseSearchCoursesRequest_criterianame Criterianame { get; set; }
#endif
        /// <summary>Search term</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest.CoreCourseSearchCoursesRequest_criteriavalue? Criteriavalue { get; set; }
#nullable restore
#else
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest.CoreCourseSearchCoursesRequest_criteriavalue Criteriavalue { get; set; }
#endif
        /// <summary>Limit to enrolled courses only</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest.CoreCourseSearchCoursesRequest_limittoenrolled? Limittoenrolled { get; set; }
#nullable restore
#else
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest.CoreCourseSearchCoursesRequest_limittoenrolled Limittoenrolled { get; set; }
#endif
        /// <summary>Page number</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest.CoreCourseSearchCoursesRequest_page? Page { get; set; }
#nullable restore
#else
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest.CoreCourseSearchCoursesRequest_page Page { get; set; }
#endif
        /// <summary>Number of results per page</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest.CoreCourseSearchCoursesRequest_perpage? Perpage { get; set; }
#nullable restore
#else
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest.CoreCourseSearchCoursesRequest_perpage Perpage { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest"/> and sets the default values.
        /// </summary>
        public CoreCourseSearchCoursesRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "criterianame", n => { Criterianame = n.GetObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest.CoreCourseSearchCoursesRequest_criterianame>(global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest.CoreCourseSearchCoursesRequest_criterianame.CreateFromDiscriminatorValue); } },
                { "criteriavalue", n => { Criteriavalue = n.GetObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest.CoreCourseSearchCoursesRequest_criteriavalue>(global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest.CoreCourseSearchCoursesRequest_criteriavalue.CreateFromDiscriminatorValue); } },
                { "limittoenrolled", n => { Limittoenrolled = n.GetObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest.CoreCourseSearchCoursesRequest_limittoenrolled>(global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest.CoreCourseSearchCoursesRequest_limittoenrolled.CreateFromDiscriminatorValue); } },
                { "page", n => { Page = n.GetObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest.CoreCourseSearchCoursesRequest_page>(global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest.CoreCourseSearchCoursesRequest_page.CreateFromDiscriminatorValue); } },
                { "perpage", n => { Perpage = n.GetObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest.CoreCourseSearchCoursesRequest_perpage>(global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest.CoreCourseSearchCoursesRequest_perpage.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest.CoreCourseSearchCoursesRequest_criterianame>("criterianame", Criterianame);
            writer.WriteObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest.CoreCourseSearchCoursesRequest_criteriavalue>("criteriavalue", Criteriavalue);
            writer.WriteObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest.CoreCourseSearchCoursesRequest_limittoenrolled>("limittoenrolled", Limittoenrolled);
            writer.WriteObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest.CoreCourseSearchCoursesRequest_page>("page", Page);
            writer.WriteObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest.CoreCourseSearchCoursesRequest_perpage>("perpage", Perpage);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest_criterianameMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CoreCourseSearchCoursesRequest_criterianame : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest_criterianameMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest_criterianameMember1? CoreCourseSearchCoursesRequestCriterianameMember1 { get; set; }
#nullable restore
#else
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest_criterianameMember1 CoreCourseSearchCoursesRequestCriterianameMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest.CoreCourseSearchCoursesRequest_criterianame"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest.CoreCourseSearchCoursesRequest_criterianame CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest.CoreCourseSearchCoursesRequest_criterianame();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.CoreCourseSearchCoursesRequestCriterianameMember1 = new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest_criterianameMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CoreCourseSearchCoursesRequestCriterianameMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(CoreCourseSearchCoursesRequestCriterianameMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest_criterianameMember1>(null, CoreCourseSearchCoursesRequestCriterianameMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest_criteriavalueMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CoreCourseSearchCoursesRequest_criteriavalue : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest_criteriavalueMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest_criteriavalueMember1? CoreCourseSearchCoursesRequestCriteriavalueMember1 { get; set; }
#nullable restore
#else
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest_criteriavalueMember1 CoreCourseSearchCoursesRequestCriteriavalueMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest.CoreCourseSearchCoursesRequest_criteriavalue"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest.CoreCourseSearchCoursesRequest_criteriavalue CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest.CoreCourseSearchCoursesRequest_criteriavalue();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.CoreCourseSearchCoursesRequestCriteriavalueMember1 = new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest_criteriavalueMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CoreCourseSearchCoursesRequestCriteriavalueMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(CoreCourseSearchCoursesRequestCriteriavalueMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest_criteriavalueMember1>(null, CoreCourseSearchCoursesRequestCriteriavalueMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest_limittoenrolledMember1"/>, <see cref="int"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CoreCourseSearchCoursesRequest_limittoenrolled : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest_limittoenrolledMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest_limittoenrolledMember1? CoreCourseSearchCoursesRequestLimittoenrolledMember1 { get; set; }
#nullable restore
#else
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest_limittoenrolledMember1 CoreCourseSearchCoursesRequestLimittoenrolledMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="int"/></summary>
            public int? Integer { get; set; }
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest.CoreCourseSearchCoursesRequest_limittoenrolled"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest.CoreCourseSearchCoursesRequest_limittoenrolled CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest.CoreCourseSearchCoursesRequest_limittoenrolled();
                if(parseNode.GetIntValue() is int integerValue)
                {
                    result.Integer = integerValue;
                }
                else {
                    result.CoreCourseSearchCoursesRequestLimittoenrolledMember1 = new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest_limittoenrolledMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CoreCourseSearchCoursesRequestLimittoenrolledMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(CoreCourseSearchCoursesRequestLimittoenrolledMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Integer != null)
                {
                    writer.WriteIntValue(null, Integer);
                }
                else {
                    writer.WriteObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest_limittoenrolledMember1>(null, CoreCourseSearchCoursesRequestLimittoenrolledMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest_pageMember1"/>, <see cref="int"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CoreCourseSearchCoursesRequest_page : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest_pageMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest_pageMember1? CoreCourseSearchCoursesRequestPageMember1 { get; set; }
#nullable restore
#else
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest_pageMember1 CoreCourseSearchCoursesRequestPageMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="int"/></summary>
            public int? Integer { get; set; }
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest.CoreCourseSearchCoursesRequest_page"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest.CoreCourseSearchCoursesRequest_page CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest.CoreCourseSearchCoursesRequest_page();
                if(parseNode.GetIntValue() is int integerValue)
                {
                    result.Integer = integerValue;
                }
                else {
                    result.CoreCourseSearchCoursesRequestPageMember1 = new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest_pageMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CoreCourseSearchCoursesRequestPageMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(CoreCourseSearchCoursesRequestPageMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Integer != null)
                {
                    writer.WriteIntValue(null, Integer);
                }
                else {
                    writer.WriteObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest_pageMember1>(null, CoreCourseSearchCoursesRequestPageMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest_perpageMember1"/>, <see cref="int"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CoreCourseSearchCoursesRequest_perpage : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest_perpageMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest_perpageMember1? CoreCourseSearchCoursesRequestPerpageMember1 { get; set; }
#nullable restore
#else
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest_perpageMember1 CoreCourseSearchCoursesRequestPerpageMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="int"/></summary>
            public int? Integer { get; set; }
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest.CoreCourseSearchCoursesRequest_perpage"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest.CoreCourseSearchCoursesRequest_perpage CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest.CoreCourseSearchCoursesRequest_perpage();
                if(parseNode.GetIntValue() is int integerValue)
                {
                    result.Integer = integerValue;
                }
                else {
                    result.CoreCourseSearchCoursesRequestPerpageMember1 = new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest_perpageMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CoreCourseSearchCoursesRequestPerpageMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(CoreCourseSearchCoursesRequestPerpageMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Integer != null)
                {
                    writer.WriteIntValue(null, Integer);
                }
                else {
                    writer.WriteObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCourseSearchCoursesRequest_perpageMember1>(null, CoreCourseSearchCoursesRequestPerpageMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
