// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Kursa.Infrastructure.MoodlewareAPI.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CoreCalendarGetActionEventsByCourseRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>After event ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest.CoreCalendarGetActionEventsByCourseRequest_aftereventid? Aftereventid { get; set; }
#nullable restore
#else
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest.CoreCalendarGetActionEventsByCourseRequest_aftereventid Aftereventid { get; set; }
#endif
        /// <summary>Course ID</summary>
        public int? Courseid { get; set; }
        /// <summary>Number of events to return</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest.CoreCalendarGetActionEventsByCourseRequest_limitnum? Limitnum { get; set; }
#nullable restore
#else
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest.CoreCalendarGetActionEventsByCourseRequest_limitnum Limitnum { get; set; }
#endif
        /// <summary>Time sort from (timestamp)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest.CoreCalendarGetActionEventsByCourseRequest_timesortfrom? Timesortfrom { get; set; }
#nullable restore
#else
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest.CoreCalendarGetActionEventsByCourseRequest_timesortfrom Timesortfrom { get; set; }
#endif
        /// <summary>Time sort to (timestamp)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest.CoreCalendarGetActionEventsByCourseRequest_timesortto? Timesortto { get; set; }
#nullable restore
#else
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest.CoreCalendarGetActionEventsByCourseRequest_timesortto Timesortto { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest"/> and sets the default values.
        /// </summary>
        public CoreCalendarGetActionEventsByCourseRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "aftereventid", n => { Aftereventid = n.GetObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest.CoreCalendarGetActionEventsByCourseRequest_aftereventid>(global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest.CoreCalendarGetActionEventsByCourseRequest_aftereventid.CreateFromDiscriminatorValue); } },
                { "courseid", n => { Courseid = n.GetIntValue(); } },
                { "limitnum", n => { Limitnum = n.GetObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest.CoreCalendarGetActionEventsByCourseRequest_limitnum>(global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest.CoreCalendarGetActionEventsByCourseRequest_limitnum.CreateFromDiscriminatorValue); } },
                { "timesortfrom", n => { Timesortfrom = n.GetObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest.CoreCalendarGetActionEventsByCourseRequest_timesortfrom>(global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest.CoreCalendarGetActionEventsByCourseRequest_timesortfrom.CreateFromDiscriminatorValue); } },
                { "timesortto", n => { Timesortto = n.GetObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest.CoreCalendarGetActionEventsByCourseRequest_timesortto>(global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest.CoreCalendarGetActionEventsByCourseRequest_timesortto.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest.CoreCalendarGetActionEventsByCourseRequest_aftereventid>("aftereventid", Aftereventid);
            writer.WriteIntValue("courseid", Courseid);
            writer.WriteObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest.CoreCalendarGetActionEventsByCourseRequest_limitnum>("limitnum", Limitnum);
            writer.WriteObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest.CoreCalendarGetActionEventsByCourseRequest_timesortfrom>("timesortfrom", Timesortfrom);
            writer.WriteObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest.CoreCalendarGetActionEventsByCourseRequest_timesortto>("timesortto", Timesortto);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest_aftereventidMember1"/>, <see cref="int"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CoreCalendarGetActionEventsByCourseRequest_aftereventid : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest_aftereventidMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest_aftereventidMember1? CoreCalendarGetActionEventsByCourseRequestAftereventidMember1 { get; set; }
#nullable restore
#else
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest_aftereventidMember1 CoreCalendarGetActionEventsByCourseRequestAftereventidMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="int"/></summary>
            public int? Integer { get; set; }
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest.CoreCalendarGetActionEventsByCourseRequest_aftereventid"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest.CoreCalendarGetActionEventsByCourseRequest_aftereventid CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest.CoreCalendarGetActionEventsByCourseRequest_aftereventid();
                if(parseNode.GetIntValue() is int integerValue)
                {
                    result.Integer = integerValue;
                }
                else {
                    result.CoreCalendarGetActionEventsByCourseRequestAftereventidMember1 = new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest_aftereventidMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CoreCalendarGetActionEventsByCourseRequestAftereventidMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(CoreCalendarGetActionEventsByCourseRequestAftereventidMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Integer != null)
                {
                    writer.WriteIntValue(null, Integer);
                }
                else {
                    writer.WriteObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest_aftereventidMember1>(null, CoreCalendarGetActionEventsByCourseRequestAftereventidMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest_limitnumMember1"/>, <see cref="int"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CoreCalendarGetActionEventsByCourseRequest_limitnum : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest_limitnumMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest_limitnumMember1? CoreCalendarGetActionEventsByCourseRequestLimitnumMember1 { get; set; }
#nullable restore
#else
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest_limitnumMember1 CoreCalendarGetActionEventsByCourseRequestLimitnumMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="int"/></summary>
            public int? Integer { get; set; }
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest.CoreCalendarGetActionEventsByCourseRequest_limitnum"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest.CoreCalendarGetActionEventsByCourseRequest_limitnum CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest.CoreCalendarGetActionEventsByCourseRequest_limitnum();
                if(parseNode.GetIntValue() is int integerValue)
                {
                    result.Integer = integerValue;
                }
                else {
                    result.CoreCalendarGetActionEventsByCourseRequestLimitnumMember1 = new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest_limitnumMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CoreCalendarGetActionEventsByCourseRequestLimitnumMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(CoreCalendarGetActionEventsByCourseRequestLimitnumMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Integer != null)
                {
                    writer.WriteIntValue(null, Integer);
                }
                else {
                    writer.WriteObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest_limitnumMember1>(null, CoreCalendarGetActionEventsByCourseRequestLimitnumMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest_timesortfromMember1"/>, <see cref="int"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CoreCalendarGetActionEventsByCourseRequest_timesortfrom : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest_timesortfromMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest_timesortfromMember1? CoreCalendarGetActionEventsByCourseRequestTimesortfromMember1 { get; set; }
#nullable restore
#else
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest_timesortfromMember1 CoreCalendarGetActionEventsByCourseRequestTimesortfromMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="int"/></summary>
            public int? Integer { get; set; }
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest.CoreCalendarGetActionEventsByCourseRequest_timesortfrom"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest.CoreCalendarGetActionEventsByCourseRequest_timesortfrom CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest.CoreCalendarGetActionEventsByCourseRequest_timesortfrom();
                if(parseNode.GetIntValue() is int integerValue)
                {
                    result.Integer = integerValue;
                }
                else {
                    result.CoreCalendarGetActionEventsByCourseRequestTimesortfromMember1 = new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest_timesortfromMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CoreCalendarGetActionEventsByCourseRequestTimesortfromMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(CoreCalendarGetActionEventsByCourseRequestTimesortfromMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Integer != null)
                {
                    writer.WriteIntValue(null, Integer);
                }
                else {
                    writer.WriteObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest_timesortfromMember1>(null, CoreCalendarGetActionEventsByCourseRequestTimesortfromMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest_timesorttoMember1"/>, <see cref="int"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CoreCalendarGetActionEventsByCourseRequest_timesortto : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest_timesorttoMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest_timesorttoMember1? CoreCalendarGetActionEventsByCourseRequestTimesorttoMember1 { get; set; }
#nullable restore
#else
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest_timesorttoMember1 CoreCalendarGetActionEventsByCourseRequestTimesorttoMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="int"/></summary>
            public int? Integer { get; set; }
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest.CoreCalendarGetActionEventsByCourseRequest_timesortto"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest.CoreCalendarGetActionEventsByCourseRequest_timesortto CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest.CoreCalendarGetActionEventsByCourseRequest_timesortto();
                if(parseNode.GetIntValue() is int integerValue)
                {
                    result.Integer = integerValue;
                }
                else {
                    result.CoreCalendarGetActionEventsByCourseRequestTimesorttoMember1 = new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest_timesorttoMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CoreCalendarGetActionEventsByCourseRequestTimesorttoMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(CoreCalendarGetActionEventsByCourseRequestTimesorttoMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Integer != null)
                {
                    writer.WriteIntValue(null, Integer);
                }
                else {
                    writer.WriteObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreCalendarGetActionEventsByCourseRequest_timesorttoMember1>(null, CoreCalendarGetActionEventsByCourseRequestTimesorttoMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
