// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Kursa.Infrastructure.MoodlewareAPI.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CoreFilesGetFilesRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Component name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Component { get; set; }
#nullable restore
#else
        public string Component { get; set; }
#endif
        /// <summary>Context ID</summary>
        public int? Contextid { get; set; }
        /// <summary>File area</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Filearea { get; set; }
#nullable restore
#else
        public string Filearea { get; set; }
#endif
        /// <summary>File name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreFilesGetFilesRequest.CoreFilesGetFilesRequest_filename? Filename { get; set; }
#nullable restore
#else
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreFilesGetFilesRequest.CoreFilesGetFilesRequest_filename Filename { get; set; }
#endif
        /// <summary>File path</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreFilesGetFilesRequest.CoreFilesGetFilesRequest_filepath? Filepath { get; set; }
#nullable restore
#else
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreFilesGetFilesRequest.CoreFilesGetFilesRequest_filepath Filepath { get; set; }
#endif
        /// <summary>Item ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreFilesGetFilesRequest.CoreFilesGetFilesRequest_itemid? Itemid { get; set; }
#nullable restore
#else
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreFilesGetFilesRequest.CoreFilesGetFilesRequest_itemid Itemid { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreFilesGetFilesRequest"/> and sets the default values.
        /// </summary>
        public CoreFilesGetFilesRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreFilesGetFilesRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreFilesGetFilesRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreFilesGetFilesRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "component", n => { Component = n.GetStringValue(); } },
                { "contextid", n => { Contextid = n.GetIntValue(); } },
                { "filearea", n => { Filearea = n.GetStringValue(); } },
                { "filename", n => { Filename = n.GetObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreFilesGetFilesRequest.CoreFilesGetFilesRequest_filename>(global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreFilesGetFilesRequest.CoreFilesGetFilesRequest_filename.CreateFromDiscriminatorValue); } },
                { "filepath", n => { Filepath = n.GetObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreFilesGetFilesRequest.CoreFilesGetFilesRequest_filepath>(global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreFilesGetFilesRequest.CoreFilesGetFilesRequest_filepath.CreateFromDiscriminatorValue); } },
                { "itemid", n => { Itemid = n.GetObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreFilesGetFilesRequest.CoreFilesGetFilesRequest_itemid>(global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreFilesGetFilesRequest.CoreFilesGetFilesRequest_itemid.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("component", Component);
            writer.WriteIntValue("contextid", Contextid);
            writer.WriteStringValue("filearea", Filearea);
            writer.WriteObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreFilesGetFilesRequest.CoreFilesGetFilesRequest_filename>("filename", Filename);
            writer.WriteObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreFilesGetFilesRequest.CoreFilesGetFilesRequest_filepath>("filepath", Filepath);
            writer.WriteObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreFilesGetFilesRequest.CoreFilesGetFilesRequest_itemid>("itemid", Itemid);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreFilesGetFilesRequest_filenameMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CoreFilesGetFilesRequest_filename : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreFilesGetFilesRequest_filenameMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreFilesGetFilesRequest_filenameMember1? CoreFilesGetFilesRequestFilenameMember1 { get; set; }
#nullable restore
#else
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreFilesGetFilesRequest_filenameMember1 CoreFilesGetFilesRequestFilenameMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreFilesGetFilesRequest.CoreFilesGetFilesRequest_filename"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreFilesGetFilesRequest.CoreFilesGetFilesRequest_filename CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreFilesGetFilesRequest.CoreFilesGetFilesRequest_filename();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.CoreFilesGetFilesRequestFilenameMember1 = new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreFilesGetFilesRequest_filenameMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CoreFilesGetFilesRequestFilenameMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(CoreFilesGetFilesRequestFilenameMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreFilesGetFilesRequest_filenameMember1>(null, CoreFilesGetFilesRequestFilenameMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreFilesGetFilesRequest_filepathMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CoreFilesGetFilesRequest_filepath : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreFilesGetFilesRequest_filepathMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreFilesGetFilesRequest_filepathMember1? CoreFilesGetFilesRequestFilepathMember1 { get; set; }
#nullable restore
#else
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreFilesGetFilesRequest_filepathMember1 CoreFilesGetFilesRequestFilepathMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreFilesGetFilesRequest.CoreFilesGetFilesRequest_filepath"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreFilesGetFilesRequest.CoreFilesGetFilesRequest_filepath CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreFilesGetFilesRequest.CoreFilesGetFilesRequest_filepath();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.CoreFilesGetFilesRequestFilepathMember1 = new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreFilesGetFilesRequest_filepathMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CoreFilesGetFilesRequestFilepathMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(CoreFilesGetFilesRequestFilepathMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreFilesGetFilesRequest_filepathMember1>(null, CoreFilesGetFilesRequestFilepathMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreFilesGetFilesRequest_itemidMember1"/>, <see cref="int"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CoreFilesGetFilesRequest_itemid : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreFilesGetFilesRequest_itemidMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreFilesGetFilesRequest_itemidMember1? CoreFilesGetFilesRequestItemidMember1 { get; set; }
#nullable restore
#else
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreFilesGetFilesRequest_itemidMember1 CoreFilesGetFilesRequestItemidMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="int"/></summary>
            public int? Integer { get; set; }
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreFilesGetFilesRequest.CoreFilesGetFilesRequest_itemid"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreFilesGetFilesRequest.CoreFilesGetFilesRequest_itemid CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreFilesGetFilesRequest.CoreFilesGetFilesRequest_itemid();
                if(parseNode.GetIntValue() is int integerValue)
                {
                    result.Integer = integerValue;
                }
                else {
                    result.CoreFilesGetFilesRequestItemidMember1 = new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreFilesGetFilesRequest_itemidMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CoreFilesGetFilesRequestItemidMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(CoreFilesGetFilesRequestItemidMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Integer != null)
                {
                    writer.WriteIntValue(null, Integer);
                }
                else {
                    writer.WriteObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.CoreFilesGetFilesRequest_itemidMember1>(null, CoreFilesGetFilesRequestItemidMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
