// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Kursa.Infrastructure.MoodlewareAPI.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ModQuizStartAttemptRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Force new attempt.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizStartAttemptRequest.ModQuizStartAttemptRequest_forcenew? Forcenew { get; set; }
#nullable restore
#else
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizStartAttemptRequest.ModQuizStartAttemptRequest_forcenew Forcenew { get; set; }
#endif
        /// <summary>Pre-flight data as list of {name, value} objects (JSON or CSV).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizStartAttemptRequest.ModQuizStartAttemptRequest_preflightdata? Preflightdata { get; set; }
#nullable restore
#else
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizStartAttemptRequest.ModQuizStartAttemptRequest_preflightdata Preflightdata { get; set; }
#endif
        /// <summary>Quiz ID</summary>
        public int? Quizid { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizStartAttemptRequest"/> and sets the default values.
        /// </summary>
        public ModQuizStartAttemptRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizStartAttemptRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizStartAttemptRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizStartAttemptRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "forcenew", n => { Forcenew = n.GetObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizStartAttemptRequest.ModQuizStartAttemptRequest_forcenew>(global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizStartAttemptRequest.ModQuizStartAttemptRequest_forcenew.CreateFromDiscriminatorValue); } },
                { "preflightdata", n => { Preflightdata = n.GetObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizStartAttemptRequest.ModQuizStartAttemptRequest_preflightdata>(global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizStartAttemptRequest.ModQuizStartAttemptRequest_preflightdata.CreateFromDiscriminatorValue); } },
                { "quizid", n => { Quizid = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizStartAttemptRequest.ModQuizStartAttemptRequest_forcenew>("forcenew", Forcenew);
            writer.WriteObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizStartAttemptRequest.ModQuizStartAttemptRequest_preflightdata>("preflightdata", Preflightdata);
            writer.WriteIntValue("quizid", Quizid);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="bool"/>, <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizStartAttemptRequest_forcenewMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ModQuizStartAttemptRequest_forcenew : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="bool"/></summary>
            public bool? Boolean { get; set; }
            /// <summary>Composed type representation for type <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizStartAttemptRequest_forcenewMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizStartAttemptRequest_forcenewMember1? ModQuizStartAttemptRequestForcenewMember1 { get; set; }
#nullable restore
#else
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizStartAttemptRequest_forcenewMember1 ModQuizStartAttemptRequestForcenewMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizStartAttemptRequest.ModQuizStartAttemptRequest_forcenew"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizStartAttemptRequest.ModQuizStartAttemptRequest_forcenew CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizStartAttemptRequest.ModQuizStartAttemptRequest_forcenew();
                if(parseNode.GetBoolValue() is bool booleanValue)
                {
                    result.Boolean = booleanValue;
                }
                else {
                    result.ModQuizStartAttemptRequestForcenewMember1 = new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizStartAttemptRequest_forcenewMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ModQuizStartAttemptRequestForcenewMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ModQuizStartAttemptRequestForcenewMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Boolean != null)
                {
                    writer.WriteBoolValue(null, Boolean);
                }
                else {
                    writer.WriteObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizStartAttemptRequest_forcenewMember1>(null, ModQuizStartAttemptRequestForcenewMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizStartAttemptRequest_preflightdataMember1"/>, <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizStartAttemptRequest_preflightdataMember2"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ModQuizStartAttemptRequest_preflightdata : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizStartAttemptRequest_preflightdataMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizStartAttemptRequest_preflightdataMember1? ModQuizStartAttemptRequestPreflightdataMember1 { get; set; }
#nullable restore
#else
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizStartAttemptRequest_preflightdataMember1 ModQuizStartAttemptRequestPreflightdataMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizStartAttemptRequest_preflightdataMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizStartAttemptRequest_preflightdataMember2? ModQuizStartAttemptRequestPreflightdataMember2 { get; set; }
#nullable restore
#else
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizStartAttemptRequest_preflightdataMember2 ModQuizStartAttemptRequestPreflightdataMember2 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizStartAttemptRequest.ModQuizStartAttemptRequest_preflightdata"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizStartAttemptRequest.ModQuizStartAttemptRequest_preflightdata CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizStartAttemptRequest.ModQuizStartAttemptRequest_preflightdata();
                result.ModQuizStartAttemptRequestPreflightdataMember1 = new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizStartAttemptRequest_preflightdataMember1();
                result.ModQuizStartAttemptRequestPreflightdataMember2 = new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizStartAttemptRequest_preflightdataMember2();
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ModQuizStartAttemptRequestPreflightdataMember1 != null || ModQuizStartAttemptRequestPreflightdataMember2 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ModQuizStartAttemptRequestPreflightdataMember1, ModQuizStartAttemptRequestPreflightdataMember2);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                writer.WriteObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizStartAttemptRequest_preflightdataMember1>(null, ModQuizStartAttemptRequestPreflightdataMember1, ModQuizStartAttemptRequestPreflightdataMember2);
            }
        }
    }
}
#pragma warning restore CS0618
