// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Kursa.Infrastructure.MoodlewareAPI.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ModQuizProcessAttemptRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Attempt ID</summary>
        public int? Attemptid { get; set; }
        /// <summary>Responses as list of {name, value} objects</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest.ModQuizProcessAttemptRequest_data? Data { get; set; }
#nullable restore
#else
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest.ModQuizProcessAttemptRequest_data Data { get; set; }
#endif
        /// <summary>Finish the attempt</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest.ModQuizProcessAttemptRequest_finishattempt? Finishattempt { get; set; }
#nullable restore
#else
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest.ModQuizProcessAttemptRequest_finishattempt Finishattempt { get; set; }
#endif
        /// <summary>Pre-flight data as list of {name, value} objects</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest.ModQuizProcessAttemptRequest_preflightdata? Preflightdata { get; set; }
#nullable restore
#else
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest.ModQuizProcessAttemptRequest_preflightdata Preflightdata { get; set; }
#endif
        /// <summary>Time is up</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest.ModQuizProcessAttemptRequest_timeup? Timeup { get; set; }
#nullable restore
#else
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest.ModQuizProcessAttemptRequest_timeup Timeup { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest"/> and sets the default values.
        /// </summary>
        public ModQuizProcessAttemptRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "attemptid", n => { Attemptid = n.GetIntValue(); } },
                { "data", n => { Data = n.GetObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest.ModQuizProcessAttemptRequest_data>(global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest.ModQuizProcessAttemptRequest_data.CreateFromDiscriminatorValue); } },
                { "finishattempt", n => { Finishattempt = n.GetObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest.ModQuizProcessAttemptRequest_finishattempt>(global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest.ModQuizProcessAttemptRequest_finishattempt.CreateFromDiscriminatorValue); } },
                { "preflightdata", n => { Preflightdata = n.GetObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest.ModQuizProcessAttemptRequest_preflightdata>(global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest.ModQuizProcessAttemptRequest_preflightdata.CreateFromDiscriminatorValue); } },
                { "timeup", n => { Timeup = n.GetObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest.ModQuizProcessAttemptRequest_timeup>(global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest.ModQuizProcessAttemptRequest_timeup.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("attemptid", Attemptid);
            writer.WriteObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest.ModQuizProcessAttemptRequest_data>("data", Data);
            writer.WriteObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest.ModQuizProcessAttemptRequest_finishattempt>("finishattempt", Finishattempt);
            writer.WriteObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest.ModQuizProcessAttemptRequest_preflightdata>("preflightdata", Preflightdata);
            writer.WriteObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest.ModQuizProcessAttemptRequest_timeup>("timeup", Timeup);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest_dataMember1"/>, <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest_dataMember2"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ModQuizProcessAttemptRequest_data : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest_dataMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest_dataMember1? ModQuizProcessAttemptRequestDataMember1 { get; set; }
#nullable restore
#else
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest_dataMember1 ModQuizProcessAttemptRequestDataMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest_dataMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest_dataMember2? ModQuizProcessAttemptRequestDataMember2 { get; set; }
#nullable restore
#else
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest_dataMember2 ModQuizProcessAttemptRequestDataMember2 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest.ModQuizProcessAttemptRequest_data"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest.ModQuizProcessAttemptRequest_data CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest.ModQuizProcessAttemptRequest_data();
                result.ModQuizProcessAttemptRequestDataMember1 = new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest_dataMember1();
                result.ModQuizProcessAttemptRequestDataMember2 = new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest_dataMember2();
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ModQuizProcessAttemptRequestDataMember1 != null || ModQuizProcessAttemptRequestDataMember2 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ModQuizProcessAttemptRequestDataMember1, ModQuizProcessAttemptRequestDataMember2);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                writer.WriteObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest_dataMember1>(null, ModQuizProcessAttemptRequestDataMember1, ModQuizProcessAttemptRequestDataMember2);
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="bool"/>, <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest_finishattemptMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ModQuizProcessAttemptRequest_finishattempt : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="bool"/></summary>
            public bool? Boolean { get; set; }
            /// <summary>Composed type representation for type <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest_finishattemptMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest_finishattemptMember1? ModQuizProcessAttemptRequestFinishattemptMember1 { get; set; }
#nullable restore
#else
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest_finishattemptMember1 ModQuizProcessAttemptRequestFinishattemptMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest.ModQuizProcessAttemptRequest_finishattempt"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest.ModQuizProcessAttemptRequest_finishattempt CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest.ModQuizProcessAttemptRequest_finishattempt();
                if(parseNode.GetBoolValue() is bool booleanValue)
                {
                    result.Boolean = booleanValue;
                }
                else {
                    result.ModQuizProcessAttemptRequestFinishattemptMember1 = new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest_finishattemptMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ModQuizProcessAttemptRequestFinishattemptMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ModQuizProcessAttemptRequestFinishattemptMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Boolean != null)
                {
                    writer.WriteBoolValue(null, Boolean);
                }
                else {
                    writer.WriteObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest_finishattemptMember1>(null, ModQuizProcessAttemptRequestFinishattemptMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest_preflightdataMember1"/>, <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest_preflightdataMember2"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ModQuizProcessAttemptRequest_preflightdata : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest_preflightdataMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest_preflightdataMember1? ModQuizProcessAttemptRequestPreflightdataMember1 { get; set; }
#nullable restore
#else
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest_preflightdataMember1 ModQuizProcessAttemptRequestPreflightdataMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest_preflightdataMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest_preflightdataMember2? ModQuizProcessAttemptRequestPreflightdataMember2 { get; set; }
#nullable restore
#else
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest_preflightdataMember2 ModQuizProcessAttemptRequestPreflightdataMember2 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest.ModQuizProcessAttemptRequest_preflightdata"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest.ModQuizProcessAttemptRequest_preflightdata CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest.ModQuizProcessAttemptRequest_preflightdata();
                result.ModQuizProcessAttemptRequestPreflightdataMember1 = new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest_preflightdataMember1();
                result.ModQuizProcessAttemptRequestPreflightdataMember2 = new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest_preflightdataMember2();
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ModQuizProcessAttemptRequestPreflightdataMember1 != null || ModQuizProcessAttemptRequestPreflightdataMember2 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ModQuizProcessAttemptRequestPreflightdataMember1, ModQuizProcessAttemptRequestPreflightdataMember2);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                writer.WriteObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest_preflightdataMember1>(null, ModQuizProcessAttemptRequestPreflightdataMember1, ModQuizProcessAttemptRequestPreflightdataMember2);
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="bool"/>, <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest_timeupMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ModQuizProcessAttemptRequest_timeup : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="bool"/></summary>
            public bool? Boolean { get; set; }
            /// <summary>Composed type representation for type <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest_timeupMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest_timeupMember1? ModQuizProcessAttemptRequestTimeupMember1 { get; set; }
#nullable restore
#else
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest_timeupMember1 ModQuizProcessAttemptRequestTimeupMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest.ModQuizProcessAttemptRequest_timeup"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest.ModQuizProcessAttemptRequest_timeup CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest.ModQuizProcessAttemptRequest_timeup();
                if(parseNode.GetBoolValue() is bool booleanValue)
                {
                    result.Boolean = booleanValue;
                }
                else {
                    result.ModQuizProcessAttemptRequestTimeupMember1 = new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest_timeupMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ModQuizProcessAttemptRequestTimeupMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ModQuizProcessAttemptRequestTimeupMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Boolean != null)
                {
                    writer.WriteBoolValue(null, Boolean);
                }
                else {
                    writer.WriteObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.ModQuizProcessAttemptRequest_timeupMember1>(null, ModQuizProcessAttemptRequestTimeupMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
