// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Kursa.Infrastructure.MoodlewareAPI.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Process_quiz_attempt_params : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Attempt ID</summary>
        public int? Attemptid { get; set; }
        /// <summary>Question responses data</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params.Process_quiz_attempt_params_data? Data { get; set; }
#nullable restore
#else
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params.Process_quiz_attempt_params_data Data { get; set; }
#endif
        /// <summary>Finish the attempt</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params.Process_quiz_attempt_params_finishattempt? Finishattempt { get; set; }
#nullable restore
#else
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params.Process_quiz_attempt_params_finishattempt Finishattempt { get; set; }
#endif
        /// <summary>Moodle site URL</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MoodleUrl { get; set; }
#nullable restore
#else
        public string MoodleUrl { get; set; }
#endif
        /// <summary>Pre-flight check data</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params.Process_quiz_attempt_params_preflightdata? Preflightdata { get; set; }
#nullable restore
#else
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params.Process_quiz_attempt_params_preflightdata Preflightdata { get; set; }
#endif
        /// <summary>Time is up</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params.Process_quiz_attempt_params_timeup? Timeup { get; set; }
#nullable restore
#else
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params.Process_quiz_attempt_params_timeup Timeup { get; set; }
#endif
        /// <summary>Moodle API token</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Token { get; set; }
#nullable restore
#else
        public string Token { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params"/> and sets the default values.
        /// </summary>
        public Process_quiz_attempt_params()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "attemptid", n => { Attemptid = n.GetIntValue(); } },
                { "data", n => { Data = n.GetObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params.Process_quiz_attempt_params_data>(global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params.Process_quiz_attempt_params_data.CreateFromDiscriminatorValue); } },
                { "finishattempt", n => { Finishattempt = n.GetObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params.Process_quiz_attempt_params_finishattempt>(global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params.Process_quiz_attempt_params_finishattempt.CreateFromDiscriminatorValue); } },
                { "moodle_url", n => { MoodleUrl = n.GetStringValue(); } },
                { "preflightdata", n => { Preflightdata = n.GetObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params.Process_quiz_attempt_params_preflightdata>(global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params.Process_quiz_attempt_params_preflightdata.CreateFromDiscriminatorValue); } },
                { "timeup", n => { Timeup = n.GetObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params.Process_quiz_attempt_params_timeup>(global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params.Process_quiz_attempt_params_timeup.CreateFromDiscriminatorValue); } },
                { "token", n => { Token = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("attemptid", Attemptid);
            writer.WriteObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params.Process_quiz_attempt_params_data>("data", Data);
            writer.WriteObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params.Process_quiz_attempt_params_finishattempt>("finishattempt", Finishattempt);
            writer.WriteStringValue("moodle_url", MoodleUrl);
            writer.WriteObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params.Process_quiz_attempt_params_preflightdata>("preflightdata", Preflightdata);
            writer.WriteObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params.Process_quiz_attempt_params_timeup>("timeup", Timeup);
            writer.WriteStringValue("token", Token);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params_dataMember1"/>, List&lt;string&gt;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Process_quiz_attempt_params_data : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params_dataMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params_dataMember1? ProcessQuizAttemptParamsDataMember1 { get; set; }
#nullable restore
#else
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params_dataMember1 ProcessQuizAttemptParamsDataMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type List&lt;string&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public List<string>? String { get; set; }
#nullable restore
#else
            public List<string> String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params.Process_quiz_attempt_params_data"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params.Process_quiz_attempt_params_data CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params.Process_quiz_attempt_params_data();
                if(parseNode.GetCollectionOfPrimitiveValues<string>()?.AsList() is List<string> stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.ProcessQuizAttemptParamsDataMember1 = new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params_dataMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ProcessQuizAttemptParamsDataMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ProcessQuizAttemptParamsDataMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteCollectionOfPrimitiveValues<string>(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params_dataMember1>(null, ProcessQuizAttemptParamsDataMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="bool"/>, <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params_finishattemptMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Process_quiz_attempt_params_finishattempt : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="bool"/></summary>
            public bool? Boolean { get; set; }
            /// <summary>Composed type representation for type <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params_finishattemptMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params_finishattemptMember1? ProcessQuizAttemptParamsFinishattemptMember1 { get; set; }
#nullable restore
#else
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params_finishattemptMember1 ProcessQuizAttemptParamsFinishattemptMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params.Process_quiz_attempt_params_finishattempt"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params.Process_quiz_attempt_params_finishattempt CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params.Process_quiz_attempt_params_finishattempt();
                if(parseNode.GetBoolValue() is bool booleanValue)
                {
                    result.Boolean = booleanValue;
                }
                else {
                    result.ProcessQuizAttemptParamsFinishattemptMember1 = new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params_finishattemptMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ProcessQuizAttemptParamsFinishattemptMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ProcessQuizAttemptParamsFinishattemptMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Boolean != null)
                {
                    writer.WriteBoolValue(null, Boolean);
                }
                else {
                    writer.WriteObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params_finishattemptMember1>(null, ProcessQuizAttemptParamsFinishattemptMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params_preflightdataMember1"/>, List&lt;string&gt;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Process_quiz_attempt_params_preflightdata : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params_preflightdataMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params_preflightdataMember1? ProcessQuizAttemptParamsPreflightdataMember1 { get; set; }
#nullable restore
#else
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params_preflightdataMember1 ProcessQuizAttemptParamsPreflightdataMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type List&lt;string&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public List<string>? String { get; set; }
#nullable restore
#else
            public List<string> String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params.Process_quiz_attempt_params_preflightdata"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params.Process_quiz_attempt_params_preflightdata CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params.Process_quiz_attempt_params_preflightdata();
                if(parseNode.GetCollectionOfPrimitiveValues<string>()?.AsList() is List<string> stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.ProcessQuizAttemptParamsPreflightdataMember1 = new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params_preflightdataMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ProcessQuizAttemptParamsPreflightdataMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ProcessQuizAttemptParamsPreflightdataMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteCollectionOfPrimitiveValues<string>(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params_preflightdataMember1>(null, ProcessQuizAttemptParamsPreflightdataMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="bool"/>, <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params_timeupMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Process_quiz_attempt_params_timeup : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="bool"/></summary>
            public bool? Boolean { get; set; }
            /// <summary>Composed type representation for type <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params_timeupMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params_timeupMember1? ProcessQuizAttemptParamsTimeupMember1 { get; set; }
#nullable restore
#else
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params_timeupMember1 ProcessQuizAttemptParamsTimeupMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params.Process_quiz_attempt_params_timeup"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params.Process_quiz_attempt_params_timeup CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params.Process_quiz_attempt_params_timeup();
                if(parseNode.GetBoolValue() is bool booleanValue)
                {
                    result.Boolean = booleanValue;
                }
                else {
                    result.ProcessQuizAttemptParamsTimeupMember1 = new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params_timeupMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ProcessQuizAttemptParamsTimeupMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ProcessQuizAttemptParamsTimeupMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Boolean != null)
                {
                    writer.WriteBoolValue(null, Boolean);
                }
                else {
                    writer.WriteObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Process_quiz_attempt_params_timeupMember1>(null, ProcessQuizAttemptParamsTimeupMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
