// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Kursa.Infrastructure.MoodlewareAPI.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Start_quiz_attempt_params : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Force new attempt</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Start_quiz_attempt_params.Start_quiz_attempt_params_forcenew? Forcenew { get; set; }
#nullable restore
#else
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Start_quiz_attempt_params.Start_quiz_attempt_params_forcenew Forcenew { get; set; }
#endif
        /// <summary>Moodle site URL</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MoodleUrl { get; set; }
#nullable restore
#else
        public string MoodleUrl { get; set; }
#endif
        /// <summary>Pre-flight check data</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Start_quiz_attempt_params.Start_quiz_attempt_params_preflightdata? Preflightdata { get; set; }
#nullable restore
#else
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Start_quiz_attempt_params.Start_quiz_attempt_params_preflightdata Preflightdata { get; set; }
#endif
        /// <summary>Quiz ID</summary>
        public int? Quizid { get; set; }
        /// <summary>Moodle API token</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Token { get; set; }
#nullable restore
#else
        public string Token { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Start_quiz_attempt_params"/> and sets the default values.
        /// </summary>
        public Start_quiz_attempt_params()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Start_quiz_attempt_params"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Start_quiz_attempt_params CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Start_quiz_attempt_params();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "forcenew", n => { Forcenew = n.GetObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Start_quiz_attempt_params.Start_quiz_attempt_params_forcenew>(global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Start_quiz_attempt_params.Start_quiz_attempt_params_forcenew.CreateFromDiscriminatorValue); } },
                { "moodle_url", n => { MoodleUrl = n.GetStringValue(); } },
                { "preflightdata", n => { Preflightdata = n.GetObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Start_quiz_attempt_params.Start_quiz_attempt_params_preflightdata>(global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Start_quiz_attempt_params.Start_quiz_attempt_params_preflightdata.CreateFromDiscriminatorValue); } },
                { "quizid", n => { Quizid = n.GetIntValue(); } },
                { "token", n => { Token = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Start_quiz_attempt_params.Start_quiz_attempt_params_forcenew>("forcenew", Forcenew);
            writer.WriteStringValue("moodle_url", MoodleUrl);
            writer.WriteObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Start_quiz_attempt_params.Start_quiz_attempt_params_preflightdata>("preflightdata", Preflightdata);
            writer.WriteIntValue("quizid", Quizid);
            writer.WriteStringValue("token", Token);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="bool"/>, <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Start_quiz_attempt_params_forcenewMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Start_quiz_attempt_params_forcenew : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="bool"/></summary>
            public bool? Boolean { get; set; }
            /// <summary>Composed type representation for type <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Start_quiz_attempt_params_forcenewMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Start_quiz_attempt_params_forcenewMember1? StartQuizAttemptParamsForcenewMember1 { get; set; }
#nullable restore
#else
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Start_quiz_attempt_params_forcenewMember1 StartQuizAttemptParamsForcenewMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Start_quiz_attempt_params.Start_quiz_attempt_params_forcenew"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Start_quiz_attempt_params.Start_quiz_attempt_params_forcenew CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Start_quiz_attempt_params.Start_quiz_attempt_params_forcenew();
                if(parseNode.GetBoolValue() is bool booleanValue)
                {
                    result.Boolean = booleanValue;
                }
                else {
                    result.StartQuizAttemptParamsForcenewMember1 = new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Start_quiz_attempt_params_forcenewMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(StartQuizAttemptParamsForcenewMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(StartQuizAttemptParamsForcenewMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Boolean != null)
                {
                    writer.WriteBoolValue(null, Boolean);
                }
                else {
                    writer.WriteObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Start_quiz_attempt_params_forcenewMember1>(null, StartQuizAttemptParamsForcenewMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Start_quiz_attempt_params_preflightdataMember1"/>, List&lt;string&gt;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Start_quiz_attempt_params_preflightdata : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Start_quiz_attempt_params_preflightdataMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Start_quiz_attempt_params_preflightdataMember1? StartQuizAttemptParamsPreflightdataMember1 { get; set; }
#nullable restore
#else
            public global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Start_quiz_attempt_params_preflightdataMember1 StartQuizAttemptParamsPreflightdataMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type List&lt;string&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public List<string>? String { get; set; }
#nullable restore
#else
            public List<string> String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Start_quiz_attempt_params.Start_quiz_attempt_params_preflightdata"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Start_quiz_attempt_params.Start_quiz_attempt_params_preflightdata CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Start_quiz_attempt_params.Start_quiz_attempt_params_preflightdata();
                if(parseNode.GetCollectionOfPrimitiveValues<string>()?.AsList() is List<string> stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.StartQuizAttemptParamsPreflightdataMember1 = new global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Start_quiz_attempt_params_preflightdataMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(StartQuizAttemptParamsPreflightdataMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(StartQuizAttemptParamsPreflightdataMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteCollectionOfPrimitiveValues<string>(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Kursa.Infrastructure.MoodlewareAPI.Client.Models.Start_quiz_attempt_params_preflightdataMember1>(null, StartQuizAttemptParamsPreflightdataMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
