// <auto-generated/>
#pragma warning disable CS0618
using Kursa.Infrastructure.MoodlewareAPI.Client.Secure.Check;
using Kursa.Infrastructure.MoodlewareAPI.Client.Secure.Login;
using Kursa.Infrastructure.MoodlewareAPI.Client.Secure.Logout;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Kursa.Infrastructure.MoodlewareAPI.Client.Secure
{
    /// <summary>
    /// Builds and executes requests for operations under \secure
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SecureRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The check property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Secure.Check.CheckRequestBuilder Check
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Secure.Check.CheckRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The login property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Secure.Login.LoginRequestBuilder Login
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Secure.Login.LoginRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The logout property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Secure.Logout.LogoutRequestBuilder Logout
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Secure.Logout.LogoutRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Secure.SecureRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SecureRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/secure", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Secure.SecureRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SecureRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/secure", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
