export * from './analytics.service';
import { AnalyticsService } from './analytics.service';
export * from './app.service';
import { AppService } from './app.service';
export * from './auth.service';
import { AuthService } from './auth.service';
export * from './chat.service';
import { ChatService } from './chat.service';
export * from './flashcards.service';
import { FlashcardsService } from './flashcards.service';
export * from './graph.service';
import { GraphService } from './graph.service';
export * from './moodle.service';
import { MoodleService } from './moodle.service';
export * from './pinnedContents.service';
import { PinnedContentsService } from './pinnedContents.service';
export * from './quizzes.service';
import { QuizzesService } from './quizzes.service';
export * from './recordings.service';
import { RecordingsService } from './recordings.service';
export * from './studySessions.service';
import { StudySessionsService } from './studySessions.service';
export * from './suggestions.service';
import { SuggestionsService } from './suggestions.service';
export * from './summaries.service';
import { SummariesService } from './summaries.service';
export * from './users.service';
import { UsersService } from './users.service';
export const APIS = [AnalyticsService, AppService, AuthService, ChatService, FlashcardsService, GraphService, MoodleService, PinnedContentsService, QuizzesService, RecordingsService, StudySessionsService, SuggestionsService, SummariesService, UsersService];
