// <auto-generated/>
#pragma warning disable CS0618
using Kursa.Infrastructure.MoodlewareAPI.Client.Core.Calendar.GetActionEventsByCourse;
using Kursa.Infrastructure.MoodlewareAPI.Client.Core.Calendar.GetCalendarEvents;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Kursa.Infrastructure.MoodlewareAPI.Client.Core.Calendar
{
    /// <summary>
    /// Builds and executes requests for operations under \core\calendar
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CalendarRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The getActionEventsByCourse property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Core.Calendar.GetActionEventsByCourse.GetActionEventsByCourseRequestBuilder GetActionEventsByCourse
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Core.Calendar.GetActionEventsByCourse.GetActionEventsByCourseRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The getCalendarEvents property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Core.Calendar.GetCalendarEvents.GetCalendarEventsRequestBuilder GetCalendarEvents
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Core.Calendar.GetCalendarEvents.GetCalendarEventsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Core.Calendar.CalendarRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CalendarRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/core/calendar", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Core.Calendar.CalendarRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CalendarRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/core/calendar", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
