// <auto-generated/>
#pragma warning disable CS0618
using Kursa.Infrastructure.MoodlewareAPI.Client.Core.Message.GetContacts;
using Kursa.Infrastructure.MoodlewareAPI.Client.Core.Message.GetMessages;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Kursa.Infrastructure.MoodlewareAPI.Client.Core.Message
{
    /// <summary>
    /// Builds and executes requests for operations under \core\message
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MessageRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The getContacts property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Core.Message.GetContacts.GetContactsRequestBuilder GetContacts
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Core.Message.GetContacts.GetContactsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The getMessages property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Core.Message.GetMessages.GetMessagesRequestBuilder GetMessages
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Core.Message.GetMessages.GetMessagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Core.Message.MessageRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MessageRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/core/message", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Core.Message.MessageRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MessageRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/core/message", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
