// <auto-generated/>
#pragma warning disable CS0618
using Kursa.Infrastructure.MoodlewareAPI.Client.Core.Webservice.GetSiteInfo;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Kursa.Infrastructure.MoodlewareAPI.Client.Core.Webservice
{
    /// <summary>
    /// Builds and executes requests for operations under \core\webservice
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WebserviceRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The getSiteInfo property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Core.Webservice.GetSiteInfo.GetSiteInfoRequestBuilder GetSiteInfo
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Core.Webservice.GetSiteInfo.GetSiteInfoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Core.Webservice.WebserviceRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WebserviceRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/core/webservice", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Core.Webservice.WebserviceRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WebserviceRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/core/webservice", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
