// <auto-generated/>
#pragma warning disable CS0618
using Kursa.Infrastructure.MoodlewareAPI.Client.Tool.Lp.GetLearningPlans;
using Kursa.Infrastructure.MoodlewareAPI.Client.Tool.Lp.GetUserCompetenciesInCourse;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Kursa.Infrastructure.MoodlewareAPI.Client.Tool.Lp
{
    /// <summary>
    /// Builds and executes requests for operations under \tool\lp
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LpRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The getLearningPlans property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Tool.Lp.GetLearningPlans.GetLearningPlansRequestBuilder GetLearningPlans
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Tool.Lp.GetLearningPlans.GetLearningPlansRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The getUserCompetenciesInCourse property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Tool.Lp.GetUserCompetenciesInCourse.GetUserCompetenciesInCourseRequestBuilder GetUserCompetenciesInCourse
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Tool.Lp.GetUserCompetenciesInCourse.GetUserCompetenciesInCourseRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Tool.Lp.LpRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LpRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tool/lp", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Tool.Lp.LpRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LpRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tool/lp", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
