/**
 * Kursa.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OidcConfigResponse } from './oidcConfigResponse';


export interface AppInfoResponse { 
    version?: string | null;
    environment?: string | null;
    isHealthy?: boolean;
    oidc?: OidcConfigResponse;
}

