/**
 * Kursa.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ChatMessageDto { 
    id?: string;
    role?: string | null;
    content?: string | null;
    citations?: string | null;
    tokensUsed?: number;
    createdAt?: string;
}

