/**
 * Kursa.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChatMessageDto } from './chatMessageDto';
import { CitationDto } from './citationDto';


export interface ChatResponseDto { 
    message?: ChatMessageDto;
    sources?: Array<CitationDto> | null;
}

