/**
 * Kursa.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CitationDto { 
    contentId?: string;
    contentTitle?: string | null;
    chunkText?: string | null;
    score?: number;
    sourceUrl?: string | null;
}

