/**
 * Kursa.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DiscussionViewDto { 
    id?: number;
    title?: string | null;
    message?: string | null;
    author?: string | null;
    authorAvatar?: string | null;
    createdAt?: string;
    modifiedAt?: string;
    replyCount?: number;
    isPinned?: boolean;
}

