/**
 * Kursa.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FlashcardType } from './flashcardType';


export interface FlashcardDto { 
    id?: string;
    front?: string | null;
    back?: string | null;
    type?: FlashcardType;
    repetitions?: number;
    easeFactor?: number;
    intervalDays?: number;
    nextReviewAt?: string | null;
    lastReviewedAt?: string | null;
}
export namespace FlashcardDto {
}


