/**
 * Kursa.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ForumViewDto { 
    id?: number;
    courseId?: number;
    name?: string | null;
    description?: string | null;
    type?: string | null;
    discussionCount?: number;
    lastModified?: string | null;
}

