/**
 * Kursa.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GradeViewDto { 
    id?: number;
    courseId?: number;
    courseName?: string | null;
    itemName?: string | null;
    itemType?: string | null;
    itemModule?: string | null;
    grade?: number | null;
    gradeFormatted?: string | null;
    gradeMin?: number;
    gradeMax?: number;
    percentage?: string | null;
    feedback?: string | null;
    weight?: string | null;
}

