/**
 * Kursa.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MoodleCourseDto { 
    id?: number;
    shortName?: string | null;
    fullName?: string | null;
    summary?: string | null;
    startDate?: number;
    endDate?: number;
    visible?: number;
    courseImage?: string | null;
    progress?: number | null;
    completed?: boolean | null;
    category?: number;
}

