/**
 * Kursa.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MoodleContentDto } from './moodleContentDto';


export interface MoodleModuleDto { 
    id?: number;
    name?: string | null;
    modName?: string | null;
    modPlural?: string | null;
    description?: string | null;
    url?: string | null;
    visible?: number;
    contents?: Array<MoodleContentDto> | null;
}

