/**
 * Kursa.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MoodleModuleDto } from './moodleModuleDto';


export interface MoodleCourseSectionDto { 
    id?: number;
    name?: string | null;
    summary?: string | null;
    section?: number;
    visible?: number;
    modules?: Array<MoodleModuleDto> | null;
}

