/**
 * Kursa.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OneNotePageDto { 
    id?: string | null;
    title?: string | null;
    createdDateTime?: string | null;
    lastModifiedDateTime?: string | null;
    contentUrl?: string | null;
}

