/**
 * Kursa.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OverviewStats { 
    totalStudySessions?: number;
    totalStudyTimeSeconds?: number;
    totalQuizzesTaken?: number;
    totalCardsReviewed?: number;
    totalPinnedContents?: number;
    totalPomodoros?: number;
}

