/**
 * Kursa.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PinnedContentDto { 
    id?: string;
    contentId?: string;
    contentTitle?: string | null;
    contentDescription?: string | null;
    contentType?: string | null;
    url?: string | null;
    isStarred?: boolean;
    isIndexed?: boolean;
    notes?: string | null;
    pinnedAt?: string;
}

