/**
 * Kursa.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QuestionType } from './questionType';


export interface QuizQuestionDto { 
    id?: string;
    questionText?: string | null;
    type?: QuestionType;
    options?: Array<string> | null;
    orderIndex?: number;
}
export namespace QuizQuestionDto {
}


