/**
 * Kursa.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface QuizDto { 
    id?: string;
    title?: string | null;
    topic?: string | null;
    questionCount?: number;
    durationSeconds?: number;
    attemptCount?: number;
    bestScore?: number | null;
    createdAt?: string;
}

