/**
 * Kursa.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QuizAnswerDto } from './quizAnswerDto';


export interface QuizAttemptDetailDto { 
    id?: string;
    quizId?: string;
    score?: number;
    totalQuestions?: number;
    durationSeconds?: number;
    completedAt?: string;
    answers?: Array<QuizAnswerDto> | null;
}

