/**
 * Kursa.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QuestionType } from './questionType';


export interface QuizAnswerDto { 
    questionId?: string;
    questionText?: string | null;
    type?: QuestionType;
    userAnswer?: string | null;
    correctAnswer?: string | null;
    explanation?: string | null;
    isCorrect?: boolean;
}
export namespace QuizAnswerDto {
}


