/**
 * Kursa.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TranscriptSegmentDto } from './transcriptSegmentDto';
import { RecordingStatus } from './recordingStatus';


export interface RecordingDetailDto { 
    id?: string;
    title?: string | null;
    description?: string | null;
    courseId?: string | null;
    courseTitle?: string | null;
    fileName?: string | null;
    contentType?: string | null;
    fileSizeBytes?: number;
    durationSeconds?: number | null;
    status?: RecordingStatus;
    transcriptText?: string | null;
    segments?: Array<TranscriptSegmentDto> | null;
    transcribedAt?: string | null;
    errorMessage?: string | null;
    createdAt?: string;
}
export namespace RecordingDetailDto {
}


