/**
 * Kursa.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type RecordingStatus = 0 | 1 | 2 | 3 | 4 | 5;

export const RecordingStatus = {
    NUMBER_0: 0 as RecordingStatus,
    NUMBER_1: 1 as RecordingStatus,
    NUMBER_2: 2 as RecordingStatus,
    NUMBER_3: 3 as RecordingStatus,
    NUMBER_4: 4 as RecordingStatus,
    NUMBER_5: 5 as RecordingStatus
};

