/**
 * Kursa.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RecordingStatus } from './recordingStatus';


export interface RecordingDto { 
    id?: string;
    title?: string | null;
    description?: string | null;
    courseId?: string | null;
    courseTitle?: string | null;
    fileName?: string | null;
    contentType?: string | null;
    fileSizeBytes?: number;
    durationSeconds?: number | null;
    status?: RecordingStatus;
    hasTranscript?: boolean;
    createdAt?: string;
}
export namespace RecordingDto {
}


