/**
 * Kursa.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StudySuggestionDto { 
    type?: string | null;
    title?: string | null;
    description?: string | null;
    actionUrl?: string | null;
    priority?: string | null;
}

