/**
 * Kursa.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TranscriptSegmentDto { 
    id?: string;
    orderIndex?: number;
    startSeconds?: number;
    endSeconds?: number;
    text?: string | null;
    speaker?: string | null;
}

