/**
 * Kursa.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateUserSettingsCommand { 
    theme?: string | null;
    language?: string | null;
    timezone?: string | null;
    notificationsEnabled?: boolean | null;
}

