// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_get_quizzes_by_courses
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Mod_quiz_get_quizzes_by_coursesPostResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The quizzes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_get_quizzes_by_courses.Mod_quiz_get_quizzes_by_coursesPostResponse_quizzes>? Quizzes { get; set; }
#nullable restore
#else
        public List<global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_get_quizzes_by_courses.Mod_quiz_get_quizzes_by_coursesPostResponse_quizzes> Quizzes { get; set; }
#endif
        /// <summary>The warnings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_get_quizzes_by_courses.Mod_quiz_get_quizzes_by_coursesPostResponse_warnings>? Warnings { get; set; }
#nullable restore
#else
        public List<global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_get_quizzes_by_courses.Mod_quiz_get_quizzes_by_coursesPostResponse_warnings> Warnings { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_get_quizzes_by_courses.Mod_quiz_get_quizzes_by_coursesPostResponse"/> and sets the default values.
        /// </summary>
        public Mod_quiz_get_quizzes_by_coursesPostResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_get_quizzes_by_courses.Mod_quiz_get_quizzes_by_coursesPostResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_get_quizzes_by_courses.Mod_quiz_get_quizzes_by_coursesPostResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_get_quizzes_by_courses.Mod_quiz_get_quizzes_by_coursesPostResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "quizzes", n => { Quizzes = n.GetCollectionOfObjectValues<global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_get_quizzes_by_courses.Mod_quiz_get_quizzes_by_coursesPostResponse_quizzes>(global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_get_quizzes_by_courses.Mod_quiz_get_quizzes_by_coursesPostResponse_quizzes.CreateFromDiscriminatorValue)?.AsList(); } },
                { "warnings", n => { Warnings = n.GetCollectionOfObjectValues<global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_get_quizzes_by_courses.Mod_quiz_get_quizzes_by_coursesPostResponse_warnings>(global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_get_quizzes_by_courses.Mod_quiz_get_quizzes_by_coursesPostResponse_warnings.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_get_quizzes_by_courses.Mod_quiz_get_quizzes_by_coursesPostResponse_quizzes>("quizzes", Quizzes);
            writer.WriteCollectionOfObjectValues<global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_get_quizzes_by_courses.Mod_quiz_get_quizzes_by_coursesPostResponse_warnings>("warnings", Warnings);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
