// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_get_quiz_access_information
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Mod_quiz_get_quiz_access_informationPostResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The accessrules property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Accessrules { get; set; }
#nullable restore
#else
        public List<string> Accessrules { get; set; }
#endif
        /// <summary>The activerulenames property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Activerulenames { get; set; }
#nullable restore
#else
        public List<string> Activerulenames { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The canattempt property</summary>
        public bool? Canattempt { get; set; }
        /// <summary>The canmanage property</summary>
        public bool? Canmanage { get; set; }
        /// <summary>The canpreview property</summary>
        public bool? Canpreview { get; set; }
        /// <summary>The canreviewmyattempts property</summary>
        public bool? Canreviewmyattempts { get; set; }
        /// <summary>The canviewreports property</summary>
        public bool? Canviewreports { get; set; }
        /// <summary>The preventaccessreasons property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Preventaccessreasons { get; set; }
#nullable restore
#else
        public List<string> Preventaccessreasons { get; set; }
#endif
        /// <summary>The warnings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_get_quiz_access_information.Mod_quiz_get_quiz_access_informationPostResponse_warnings>? Warnings { get; set; }
#nullable restore
#else
        public List<global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_get_quiz_access_information.Mod_quiz_get_quiz_access_informationPostResponse_warnings> Warnings { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_get_quiz_access_information.Mod_quiz_get_quiz_access_informationPostResponse"/> and sets the default values.
        /// </summary>
        public Mod_quiz_get_quiz_access_informationPostResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_get_quiz_access_information.Mod_quiz_get_quiz_access_informationPostResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_get_quiz_access_information.Mod_quiz_get_quiz_access_informationPostResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_get_quiz_access_information.Mod_quiz_get_quiz_access_informationPostResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accessrules", n => { Accessrules = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "activerulenames", n => { Activerulenames = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "canattempt", n => { Canattempt = n.GetBoolValue(); } },
                { "canmanage", n => { Canmanage = n.GetBoolValue(); } },
                { "canpreview", n => { Canpreview = n.GetBoolValue(); } },
                { "canreviewmyattempts", n => { Canreviewmyattempts = n.GetBoolValue(); } },
                { "canviewreports", n => { Canviewreports = n.GetBoolValue(); } },
                { "preventaccessreasons", n => { Preventaccessreasons = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "warnings", n => { Warnings = n.GetCollectionOfObjectValues<global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_get_quiz_access_information.Mod_quiz_get_quiz_access_informationPostResponse_warnings>(global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_get_quiz_access_information.Mod_quiz_get_quiz_access_informationPostResponse_warnings.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("accessrules", Accessrules);
            writer.WriteCollectionOfPrimitiveValues<string>("activerulenames", Activerulenames);
            writer.WriteBoolValue("canattempt", Canattempt);
            writer.WriteBoolValue("canmanage", Canmanage);
            writer.WriteBoolValue("canpreview", Canpreview);
            writer.WriteBoolValue("canreviewmyattempts", Canreviewmyattempts);
            writer.WriteBoolValue("canviewreports", Canviewreports);
            writer.WriteCollectionOfPrimitiveValues<string>("preventaccessreasons", Preventaccessreasons);
            writer.WriteCollectionOfObjectValues<global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_get_quiz_access_information.Mod_quiz_get_quiz_access_informationPostResponse_warnings>("warnings", Warnings);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
