// <auto-generated/>
#pragma warning disable CS0618
using Kursa.Infrastructure.MoodlewareAPI.Client.Core.Files.GetFiles;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Kursa.Infrastructure.MoodlewareAPI.Client.Core.Files
{
    /// <summary>
    /// Builds and executes requests for operations under \core\files
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FilesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The getFiles property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Core.Files.GetFiles.GetFilesRequestBuilder GetFiles
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Core.Files.GetFiles.GetFilesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Core.Files.FilesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FilesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/core/files", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Core.Files.FilesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FilesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/core/files", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
