// <auto-generated/>
#pragma warning disable CS0618
using Kursa.Infrastructure.MoodlewareAPI.Client.Core.Course.GetContents;
using Kursa.Infrastructure.MoodlewareAPI.Client.Core.Course.GetCoursesByField;
using Kursa.Infrastructure.MoodlewareAPI.Client.Core.Course.SearchCourses;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Kursa.Infrastructure.MoodlewareAPI.Client.Core.Course
{
    /// <summary>
    /// Builds and executes requests for operations under \core\course
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CourseRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The getContents property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Core.Course.GetContents.GetContentsRequestBuilder GetContents
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Core.Course.GetContents.GetContentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The getCoursesByField property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Core.Course.GetCoursesByField.GetCoursesByFieldRequestBuilder GetCoursesByField
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Core.Course.GetCoursesByField.GetCoursesByFieldRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The searchCourses property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Core.Course.SearchCourses.SearchCoursesRequestBuilder SearchCourses
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Core.Course.SearchCourses.SearchCoursesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Core.Course.CourseRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CourseRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/core/course", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Core.Course.CourseRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CourseRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/core/course", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
