// <auto-generated/>
#pragma warning disable CS0618
using Kursa.Infrastructure.MoodlewareAPI.Client.Auth;
using Kursa.Infrastructure.MoodlewareAPI.Client.Core_calendar_get_action_events_by_course;
using Kursa.Infrastructure.MoodlewareAPI.Client.Core_calendar_get_calendar_events;
using Kursa.Infrastructure.MoodlewareAPI.Client.Core_completion_get_activities_completion_status;
using Kursa.Infrastructure.MoodlewareAPI.Client.Core_completion_get_course_completion_status;
using Kursa.Infrastructure.MoodlewareAPI.Client.Core_completion_mark_course_self_completed;
using Kursa.Infrastructure.MoodlewareAPI.Client.Core_completion_update_activity_completion_status_manually;
using Kursa.Infrastructure.MoodlewareAPI.Client.Core_course_get_categories;
using Kursa.Infrastructure.MoodlewareAPI.Client.Core_course_get_contents;
using Kursa.Infrastructure.MoodlewareAPI.Client.Core_course_get_courses_by_field;
using Kursa.Infrastructure.MoodlewareAPI.Client.Core_course_search_courses;
using Kursa.Infrastructure.MoodlewareAPI.Client.Core_enrol_get_enrolled_users;
using Kursa.Infrastructure.MoodlewareAPI.Client.Core_enrol_get_users_courses;
using Kursa.Infrastructure.MoodlewareAPI.Client.Core_files_get_files;
using Kursa.Infrastructure.MoodlewareAPI.Client.Core_message_get_messages;
using Kursa.Infrastructure.MoodlewareAPI.Client.Core_user_get_course_user_profiles;
using Kursa.Infrastructure.MoodlewareAPI.Client.Core_user_get_user_preferences;
using Kursa.Infrastructure.MoodlewareAPI.Client.Core_user_get_users_by_field;
using Kursa.Infrastructure.MoodlewareAPI.Client.Core_webservice_get_site_info;
using Kursa.Infrastructure.MoodlewareAPI.Client.Enrol_self_enrol_user;
using Kursa.Infrastructure.MoodlewareAPI.Client.Files;
using Kursa.Infrastructure.MoodlewareAPI.Client.Gradereport_user_get_grade_items;
using Kursa.Infrastructure.MoodlewareAPI.Client.Healthz;
using Kursa.Infrastructure.MoodlewareAPI.Client.Mod_assign_get_assignments;
using Kursa.Infrastructure.MoodlewareAPI.Client.Mod_assign_get_submission_status;
using Kursa.Infrastructure.MoodlewareAPI.Client.Mod_assign_get_submissions;
using Kursa.Infrastructure.MoodlewareAPI.Client.Mod_forum_get_forum_discussions;
using Kursa.Infrastructure.MoodlewareAPI.Client.Mod_forum_get_forums_by_courses;
using Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_get_attempt_data;
using Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_get_attempt_review;
using Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_get_attempt_summary;
using Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_get_quiz_access_information;
using Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_get_quizzes_by_courses;
using Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_get_user_attempts;
using Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_process_attempt;
using Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_save_attempt;
using Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_start_attempt;
using Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_view_attempt;
using Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_view_quiz;
using Kursa.Infrastructure.MoodlewareAPI.Client.Office;
using Kursa.Infrastructure.MoodlewareAPI.Client.Secure;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Kursa.Infrastructure.MoodlewareAPI.Client
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MoodlewareApiClient : BaseRequestBuilder
    {
        /// <summary>The auth property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Auth.AuthRequestBuilder Auth
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Auth.AuthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The core_calendar_get_action_events_by_course property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_calendar_get_action_events_by_course.Core_calendar_get_action_events_by_courseRequestBuilder Core_calendar_get_action_events_by_course
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_calendar_get_action_events_by_course.Core_calendar_get_action_events_by_courseRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The core_calendar_get_calendar_events property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_calendar_get_calendar_events.Core_calendar_get_calendar_eventsRequestBuilder Core_calendar_get_calendar_events
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_calendar_get_calendar_events.Core_calendar_get_calendar_eventsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The core_completion_get_activities_completion_status property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_completion_get_activities_completion_status.Core_completion_get_activities_completion_statusRequestBuilder Core_completion_get_activities_completion_status
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_completion_get_activities_completion_status.Core_completion_get_activities_completion_statusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The core_completion_get_course_completion_status property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_completion_get_course_completion_status.Core_completion_get_course_completion_statusRequestBuilder Core_completion_get_course_completion_status
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_completion_get_course_completion_status.Core_completion_get_course_completion_statusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The core_completion_mark_course_self_completed property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_completion_mark_course_self_completed.Core_completion_mark_course_self_completedRequestBuilder Core_completion_mark_course_self_completed
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_completion_mark_course_self_completed.Core_completion_mark_course_self_completedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The core_completion_update_activity_completion_status_manually property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_completion_update_activity_completion_status_manually.Core_completion_update_activity_completion_status_manuallyRequestBuilder Core_completion_update_activity_completion_status_manually
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_completion_update_activity_completion_status_manually.Core_completion_update_activity_completion_status_manuallyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The core_course_get_categories property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_course_get_categories.Core_course_get_categoriesRequestBuilder Core_course_get_categories
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_course_get_categories.Core_course_get_categoriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The core_course_get_contents property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_course_get_contents.Core_course_get_contentsRequestBuilder Core_course_get_contents
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_course_get_contents.Core_course_get_contentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The core_course_get_courses_by_field property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_course_get_courses_by_field.Core_course_get_courses_by_fieldRequestBuilder Core_course_get_courses_by_field
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_course_get_courses_by_field.Core_course_get_courses_by_fieldRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The core_course_search_courses property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_course_search_courses.Core_course_search_coursesRequestBuilder Core_course_search_courses
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_course_search_courses.Core_course_search_coursesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The core_enrol_get_enrolled_users property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_enrol_get_enrolled_users.Core_enrol_get_enrolled_usersRequestBuilder Core_enrol_get_enrolled_users
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_enrol_get_enrolled_users.Core_enrol_get_enrolled_usersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The core_enrol_get_users_courses property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_enrol_get_users_courses.Core_enrol_get_users_coursesRequestBuilder Core_enrol_get_users_courses
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_enrol_get_users_courses.Core_enrol_get_users_coursesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The core_files_get_files property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_files_get_files.Core_files_get_filesRequestBuilder Core_files_get_files
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_files_get_files.Core_files_get_filesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The core_message_get_messages property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_message_get_messages.Core_message_get_messagesRequestBuilder Core_message_get_messages
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_message_get_messages.Core_message_get_messagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The core_user_get_course_user_profiles property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_user_get_course_user_profiles.Core_user_get_course_user_profilesRequestBuilder Core_user_get_course_user_profiles
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_user_get_course_user_profiles.Core_user_get_course_user_profilesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The core_user_get_user_preferences property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_user_get_user_preferences.Core_user_get_user_preferencesRequestBuilder Core_user_get_user_preferences
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_user_get_user_preferences.Core_user_get_user_preferencesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The core_user_get_users_by_field property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_user_get_users_by_field.Core_user_get_users_by_fieldRequestBuilder Core_user_get_users_by_field
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_user_get_users_by_field.Core_user_get_users_by_fieldRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The core_webservice_get_site_info property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_webservice_get_site_info.Core_webservice_get_site_infoRequestBuilder Core_webservice_get_site_info
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_webservice_get_site_info.Core_webservice_get_site_infoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The enrol_self_enrol_user property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Enrol_self_enrol_user.Enrol_self_enrol_userRequestBuilder Enrol_self_enrol_user
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Enrol_self_enrol_user.Enrol_self_enrol_userRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The files property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Files.FilesRequestBuilder Files
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Files.FilesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The gradereport_user_get_grade_items property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Gradereport_user_get_grade_items.Gradereport_user_get_grade_itemsRequestBuilder Gradereport_user_get_grade_items
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Gradereport_user_get_grade_items.Gradereport_user_get_grade_itemsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The healthz property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Healthz.HealthzRequestBuilder Healthz
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Healthz.HealthzRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The mod_assign_get_assignments property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_assign_get_assignments.Mod_assign_get_assignmentsRequestBuilder Mod_assign_get_assignments
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_assign_get_assignments.Mod_assign_get_assignmentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The mod_assign_get_submission_status property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_assign_get_submission_status.Mod_assign_get_submission_statusRequestBuilder Mod_assign_get_submission_status
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_assign_get_submission_status.Mod_assign_get_submission_statusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The mod_assign_get_submissions property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_assign_get_submissions.Mod_assign_get_submissionsRequestBuilder Mod_assign_get_submissions
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_assign_get_submissions.Mod_assign_get_submissionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The mod_forum_get_forum_discussions property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_forum_get_forum_discussions.Mod_forum_get_forum_discussionsRequestBuilder Mod_forum_get_forum_discussions
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_forum_get_forum_discussions.Mod_forum_get_forum_discussionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The mod_forum_get_forums_by_courses property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_forum_get_forums_by_courses.Mod_forum_get_forums_by_coursesRequestBuilder Mod_forum_get_forums_by_courses
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_forum_get_forums_by_courses.Mod_forum_get_forums_by_coursesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The mod_quiz_get_attempt_data property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_get_attempt_data.Mod_quiz_get_attempt_dataRequestBuilder Mod_quiz_get_attempt_data
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_get_attempt_data.Mod_quiz_get_attempt_dataRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The mod_quiz_get_attempt_review property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_get_attempt_review.Mod_quiz_get_attempt_reviewRequestBuilder Mod_quiz_get_attempt_review
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_get_attempt_review.Mod_quiz_get_attempt_reviewRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The mod_quiz_get_attempt_summary property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_get_attempt_summary.Mod_quiz_get_attempt_summaryRequestBuilder Mod_quiz_get_attempt_summary
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_get_attempt_summary.Mod_quiz_get_attempt_summaryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The mod_quiz_get_quiz_access_information property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_get_quiz_access_information.Mod_quiz_get_quiz_access_informationRequestBuilder Mod_quiz_get_quiz_access_information
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_get_quiz_access_information.Mod_quiz_get_quiz_access_informationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The mod_quiz_get_quizzes_by_courses property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_get_quizzes_by_courses.Mod_quiz_get_quizzes_by_coursesRequestBuilder Mod_quiz_get_quizzes_by_courses
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_get_quizzes_by_courses.Mod_quiz_get_quizzes_by_coursesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The mod_quiz_get_user_attempts property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_get_user_attempts.Mod_quiz_get_user_attemptsRequestBuilder Mod_quiz_get_user_attempts
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_get_user_attempts.Mod_quiz_get_user_attemptsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The mod_quiz_process_attempt property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_process_attempt.Mod_quiz_process_attemptRequestBuilder Mod_quiz_process_attempt
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_process_attempt.Mod_quiz_process_attemptRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The mod_quiz_save_attempt property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_save_attempt.Mod_quiz_save_attemptRequestBuilder Mod_quiz_save_attempt
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_save_attempt.Mod_quiz_save_attemptRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The mod_quiz_start_attempt property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_start_attempt.Mod_quiz_start_attemptRequestBuilder Mod_quiz_start_attempt
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_start_attempt.Mod_quiz_start_attemptRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The mod_quiz_view_attempt property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_view_attempt.Mod_quiz_view_attemptRequestBuilder Mod_quiz_view_attempt
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_view_attempt.Mod_quiz_view_attemptRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The mod_quiz_view_quiz property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_view_quiz.Mod_quiz_view_quizRequestBuilder Mod_quiz_view_quiz
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod_quiz_view_quiz.Mod_quiz_view_quizRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The office property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Office.OfficeRequestBuilder Office
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Office.OfficeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The secure property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Secure.SecureRequestBuilder Secure
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Secure.SecureRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.MoodlewareApiClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MoodlewareApiClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
        }
    }
}
#pragma warning restore CS0618
