// <auto-generated/>
#pragma warning disable CS0618
using Kursa.Infrastructure.MoodlewareAPI.Client.Call;
using Kursa.Infrastructure.MoodlewareAPI.Client.Core;
using Kursa.Infrastructure.MoodlewareAPI.Client.Enrol;
using Kursa.Infrastructure.MoodlewareAPI.Client.GetToken;
using Kursa.Infrastructure.MoodlewareAPI.Client.Gradereport;
using Kursa.Infrastructure.MoodlewareAPI.Client.Mod;
using Kursa.Infrastructure.MoodlewareAPI.Client.Tool;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Kursa.Infrastructure.MoodlewareAPI.Client
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MoodlewareApiClient : BaseRequestBuilder
    {
        /// <summary>The call property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Call.CallRequestBuilder Call
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Call.CallRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The core property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Core.CoreRequestBuilder Core
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Core.CoreRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The enrol property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Enrol.EnrolRequestBuilder Enrol
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Enrol.EnrolRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The getToken property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.GetToken.GetTokenRequestBuilder GetToken
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.GetToken.GetTokenRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The gradereport property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Gradereport.GradereportRequestBuilder Gradereport
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Gradereport.GradereportRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The mod property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod.ModRequestBuilder Mod
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Mod.ModRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tool property</summary>
        public global::Kursa.Infrastructure.MoodlewareAPI.Client.Tool.ToolRequestBuilder Tool
        {
            get => new global::Kursa.Infrastructure.MoodlewareAPI.Client.Tool.ToolRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.MoodlewareApiClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MoodlewareApiClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
        }
    }
}
#pragma warning restore CS0618
