// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Kursa.Infrastructure.MoodlewareAPI.Client.Core_completion_get_course_completion_status
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Core_completion_get_course_completion_statusPostResponse_completionstatus : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Completion aggregation method</summary>
        public int? Aggregation { get; set; }
        /// <summary>Whether the course is completed</summary>
        public bool? Completed { get; set; }
        /// <summary>List of completion criteria</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_completion_get_course_completion_status.Core_completion_get_course_completion_statusPostResponse_completionstatus_completions>? Completions { get; set; }
#nullable restore
#else
        public List<global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_completion_get_course_completion_status.Core_completion_get_course_completion_statusPostResponse_completionstatus_completions> Completions { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_completion_get_course_completion_status.Core_completion_get_course_completion_statusPostResponse_completionstatus"/> and sets the default values.
        /// </summary>
        public Core_completion_get_course_completion_statusPostResponse_completionstatus()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_completion_get_course_completion_status.Core_completion_get_course_completion_statusPostResponse_completionstatus"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_completion_get_course_completion_status.Core_completion_get_course_completion_statusPostResponse_completionstatus CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_completion_get_course_completion_status.Core_completion_get_course_completion_statusPostResponse_completionstatus();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "aggregation", n => { Aggregation = n.GetIntValue(); } },
                { "completed", n => { Completed = n.GetBoolValue(); } },
                { "completions", n => { Completions = n.GetCollectionOfObjectValues<global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_completion_get_course_completion_status.Core_completion_get_course_completion_statusPostResponse_completionstatus_completions>(global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_completion_get_course_completion_status.Core_completion_get_course_completion_statusPostResponse_completionstatus_completions.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("aggregation", Aggregation);
            writer.WriteBoolValue("completed", Completed);
            writer.WriteCollectionOfObjectValues<global::Kursa.Infrastructure.MoodlewareAPI.Client.Core_completion_get_course_completion_status.Core_completion_get_course_completion_statusPostResponse_completionstatus_completions>("completions", Completions);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
